### ISSUE TITLE
Hwa young skill 2 enhance is reverse

### ISSUE THREAD

**Issue by Drakel35** [maphe/maphe.github.io#150]
the skill +0 give her more attack and the skill +5 give her less attack

**Comment by maphe** [comment]
this is due to how the game combines different atk increases, basically if you have 7k atk on her with her S2 at +0, that means you have better gear than 7k atk with +5 S2, then you'll benefit more from buffs like atk up or vigor.

I'm not sure how to explain that better, it's probably not very clear as is, let me know if you need more details, but it's working as intended
