### ISSUE TITLE
Commander Lorina DMG Inaccurate

### ISSUE THREAD

**Issue by BaneOfSmite** [maphe/maphe.github.io#163]
Her damage on the calculator is much higher than her actual damage in game when I tried it on caides 13 by a significant value on her S1

**Comment by maphe** [comment]
I thanks for reporting, I think I remember someone reporting the same a while back, I had looked into it and couldn't find anything wrong in the calc. I guess either the multipliers got datamined wrong or there's a bug in game. Or maybe it's Caides that has a special mechanic that's not implemented in the calculator (if you have the time, can you double check against other enemies and let me know is the issue is across the board?).

I'll take another look when I find the time but can't promise anything.

**Comment by BaneOfSmite** [comment]
I figured out the issue. Upon investigating myself with different heroes attacking Caides, and using Commander Lorina to hit different bosses, It seems that her skills does scale according to target's max HP which led to Caidesreducing that scaling by 50% too. Once I reduce the health on Caides by 1/2 in the target's max HP section, the values now look accurate.

**Comment by maphe** [comment]
Ok cool, thanks for looking into it, I'll see if I can build the logic in the calc just for this boss
