### ISSUE TITLE
Expedition Damage calculating lower than in game

### ISSUE THREAD

**Issue by MariothP** [maphe/maphe.github.io#75]
The damage through the calculator is reporting low for expedition bosses. There is a bonus multiplier when being hit by units with elemental advantage. When testing versus Water Expedition lv2 boss, there seemed to be an extra +50% damage multiplier over what the calculator produced. I cannot make sense what the Earth Expedition bonus multipliers should be, as the calcs seem off by weird multipliers when elemental advantage AoE is involved combined with when Radiant Forever is and is not involved.

**Comment by maphe** [comment]
Thanks for bringing it up, I knew I was missing something. I've added the 50% extra damage from elemental advantage.

The extra damage from multi-target attacks on Earth expeditions would be a bit tough to implement, so I'm gonna skip it for now. Will try to add in the future tho so I'm just keeping the issue open for now.

**Comment by ultimatespirit** [comment]
I'm guessing you've since removed the 50% extra from the calculator, since as of this posting I couldn't see any such option, and it clearly isn't somehow turned on when pre-selecting an expedition boss.

For documentation's sake, both the enhanced element damage and the Gold Kilneode's effect in Earth expedition specifically are separate multipliers that stack additively with each other. My guess is they are implemented using the "Damage Reduction" multiplier, just using a negative multiplier for damage increase. Importantly, they are unlike the hunt elemental boosts, which stack additively with other skill or artifact multiplicative damage increases. Their wording also specifically says something like "damage _taken_ is increased/decreased" usually.

So a fire hero's non-single attack would do an additional 120% damage in Earth expedition, and a single attack by the same hero would do -20% damage (80% of the base).

Also at least currently post nerf, Earth Expedition 3's defence is somewhere between 1080 and 1090, most of my numbers point towards 1087-ish, but I had some outliers at 1080. The calculator still has it as its old value by default. Similarly Water 3 is somewhere around 900 to 910 defence now. Fire 3 is correct within usual margins of error (most of my numbers are 1346-1350 in range, calc has 1340 by default). From old data I have, Dark Gigantes 3 should have somewhere around 810-820 defence as well.

**Comment by maphe** [comment]
Hey, yeah I still need to work on that earth expedition shinanigan, I didn't forget, just been busy with other higher priorities (Straze has been a pain in the butt).

For expedition stats, did they also nerf level 3s? they only communicated on level 1s and 2s iirc.

**Comment by ultimatespirit** [comment]
They tuned down earth and water stats altogether for all levels. This is separate from the overall "all expeditions are only 7 turns now and have reduced hp" nerf. If those nerfs didn't apply to level 3s, then regardless I have plenty of data pointing to the defence numbers I gave, and not what is in the calculator now, so they must have changed at some point I guess haha.

**Comment by maphe** [comment]
All right, thanks for the input, I updated the expo3 defenses and added the earth gimmick. I also removed Expos 1 and 2 as the defense values were not valid anymore.
